spring:
  application:
    name: XMall
  datasource:
    url: jdbc:mysql://localhost:3306/xmall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 2419858473
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 5s
      # --- 连接池配置 (Lettuce) ---
      lettuce:
        pool:
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 8
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池最大阻塞等待时间（负值表示没有限制）
          max-wait: -1ms
  rabbitmq:
    host: 192.168.8.4
    port: 5672
    username: admin
    password: admin123
    virtual-host: XMall
    # 连接池配置
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        prefetch: 1
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3
        multiplier: 1.5
mybatis:
  type-aliases-package: com.renking.xmall.Entity
  mapper-locations: classpath:Mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true